# Generated by Django 5.2.13 on 2026-04-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='temp',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
