# Generated by Django 5.2.13 on 2026-04-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_branch_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='temp',
        ),
    ]
